// <auto-generated />
using CollegeApp.DataModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CollegeApp.DataModels.Migrations
{
    [DbContext(typeof(CollegeDbContext))]
    partial class CollegeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CollegeApp.DataModels.Student", b =>
                {
                    b.Property<int>("StudentNumber")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("MobilePhone")
                        .HasMaxLength(9);

                    b.HasKey("StudentNumber");

                    b.ToTable("Students");

                    b.HasData(
                        new { StudentNumber = 1, Email = "v.koloski@gmail.com", FullName = "Vladimir Koloski", MobilePhone = 76215802 }
                    );
                });

            modelBuilder.Entity("CollegeApp.DataModels.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Credits");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<string>("Semester")
                        .HasMaxLength(20);

                    b.Property<int>("StudentNumber");

                    b.HasKey("SubjectId");

                    b.HasIndex("StudentNumber");

                    b.ToTable("Subjects");

                    b.HasData(
                        new { SubjectId = 1, Credits = 8, Name = "C#", Semester = "1", StudentNumber = 1 },
                        new { SubjectId = 2, Credits = 5, Name = "SQL", Semester = "2", StudentNumber = 1 }
                    );
                });

            modelBuilder.Entity("CollegeApp.DataModels.Subject", b =>
                {
                    b.HasOne("CollegeApp.DataModels.Student", "Student")
                        .WithMany("Subjects")
                        .HasForeignKey("StudentNumber")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
